---

- name: Setup Local NGINX Server
  hosts: all
  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
  remote_user: root
  become: yes

  tasks:
  - name: Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result

  - name: Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present

  - name: Update RHEL Family Repositories (YUM)
    yum: 
      name: '*' 
      state: latest
      exclude: kernel*

  - name: Install NGINX
    yum:
      name: nginx
      state: present

  - name: Start NGINX
    service:
      name: nginx
      state: started
